### PR TITLE
Generate Tenant Report Values updated

### PR DESCRIPTION
**Pull request by u05038015**
**Description**

Description below:
Update values for the Generate Report

**Task of what was completed**

Work Completed below:

**Testing Steps**
1. Api Runs

2. Angular Builds

**Notes**

Notes below:

### CODE REVIEW

**Comment by u05038015** [comment]
Merge conflicts?

**Comment by u05038015** [comment]
image

**Comment by u05038015** [comment]
Please check when downloading my report if it is loading the table on the report with the correct values from the View Tenant page.

**Comment by u05038015** [comment]
The load details does not want to work.

Currently there is no update tenant as well.

Can't test Delete

**Review by u20422441 — APPROVED** [review]

**Pull request merged**
